### ISSUE TITLE
User creates a new garden plan

### ISSUE THREAD

**Issue by CarterNelms** [elizamarcum/greenthumb#16]
## User creates a new garden plan

As a user
In order to design a new garden
I want to create a new garden plan

Acceptance Criteria:
- User must be logged in

Usage:
- User clicks "Add Another Garden" (if they already have a garden) or "Setup your First Garden" (if this is their first garden)
- The garden is created with an auto-generated name and default dimensions
- The user is taken to the edit garden screen for that garden

**Comment by elizamarcum** [comment]
@Ashley-Wright I updated this story to match what we discussed in class today

**Comment by elizamarcum** [comment]
Resolved by #5a31be7c69a2ff07ab195fe9c9e39af241a367ca
