### ISSUE TITLE
User views garden plans on homepage

### ISSUE THREAD

**Issue by CarterNelms** [elizamarcum/greenthumb#17]
## User views garden plans on homepage

As a user
In order to see an overview of my designs for my gardens
I want to view my garden plans on the homepage

Usage:
- The home screen shows the list of plans, with a summary image of the plan and a link to the plan.
- The summary image should be generated via. a helper (e.g. GardenHelper) method that we will later fill in with a more detailed rendering of the garden.  For now, a table with the appropriate number of rows and columns will suffice.

**Comment by elizamarcum** [comment]
This is @amberagard @asejdina @ccampb13
