### ISSUE TITLE
User modifies existing garden plan

### ISSUE THREAD

**Issue by CarterNelms** [elizamarcum/greenthumb#18]
## User modifies existing garden plan

As a user
In order to reflect my actual garden
I want to customize the dimensions and name of my garden

Usage:
- User navigates to the existing garden plan
- The user sees the existing garden plan reflected in the grid view (e.g. height/width)
- User edits name/dimensions/etc.
- If changes are made to the dimensions, those changes are immediately reflected in the grid view.
- User clicks "Save Changes"
- All changes to the user's garden plan are stored to the database

**Comment by elizamarcum** [comment]
@CarterNelms Acceptance criteria are supposed to be acceptance criteria for the story, not preconditions for the story.

**Comment by elizamarcum** [comment]
This is @richmondwatkins and @SethMarch

**Comment by richmondwatkins** [comment]
Hey @elizabrock let us know if any changes need to be made.

**Comment by richmondwatkins** [comment]
Hey Eliza, we added your suggested changes. Let us know if there is anything else you would like us to do.

**Comment by richmondwatkins** [comment]
Hey Eliza, we added your requested changes. We had to leave find_by_id in the edit method because it returns true or false depending on success or failure of finding the garden in the database. The method fails when just using find.
