### ISSUE TITLE
View a Specific Plant Variety

### ISSUE THREAD

**Issue by wesmangum** [elizamarcum/greenthumb#24]
As a User
In order for user to be aware of all varieties of a plant
I want to view a specific plant variety

Acceptance Criteria:
- The view page will list the name, images, description, and Amazon URL for variety

Usage:
- User will click "Plants", select a specific Plant Category, then clicka specific plant
- User will be greeted with a short profile of the variety including:
  - Name
  - Description
  - Images
  - Amazon URL

**Comment by elizamarcum** [comment]
@mattSpell and @rachelself

**Comment by rachelself** [comment]
@elizabrock Finished this feature, let us know if any changes are needed.

**Comment by elizamarcum** [comment]
@rachelself Have you submitted a pull request for this?
