### ISSUE TITLE
Edit a Specific Plant Variety

### ISSUE THREAD

**Issue by wesmangum** [elizamarcum/greenthumb#26]
As an Admin
In order to give the user a quality experience
I want to edit the details of a plant variety

Acceptance Criteria:
- The Admin will be able to select a plant to edit from an index page
- The variety's page will have a pre-populated form with the variety's information
- When the plant is saved, it should display a confirmation message that the plant has been updated
- All validations from Creating a Plant apply

Usage:
- Admin will click "Plants", then select a variety of plant from list
- Admin will be greeted with a form populated with the variety's information, including:
  - Name
  - Description
  - Images
  - Amazon URL
- Admin will click the "Save" button to save changes
- Redirected to index page with confirmation message of saved plant

**Comment by elizamarcum** [comment]
This is @slyeargin and @nathanhood
