### ISSUE TITLE
Delete a Specific Plant Variety

### ISSUE THREAD

**Issue by wesmangum** [elizamarcum/greenthumb#28]
As an Admin
In order to protect the integrity of the site
I want to delete a plant variety

Acceptance Criteria:
- The Admin will be able to select a plant to delete from the Plants index page
- The Admin will be prompted wiht a confirmation of deleteing the plant variety
- When the plant is deleted, it should display a confirmation message

Usage:
- From the Plant page for the plant in question:
- Admin will click the "Delete" button
- Admin will be prompted to confirm the deletion
- Redirected to index page with confirmation message of deleted plant

**Comment by elizamarcum** [comment]
This is @Courey and @kelleystephens
