### ISSUE TITLE
Admin vs. User Authorization

### ISSUE THREAD

**Issue by elizamarcum** [elizamarcum/greenthumb#44]
In order to prevent users from messing with important data
As an admin
I only want admins to be able to perform certain actions

Use the cancan gem to lock down privileges, so that:
- Only admins can edit plants
- Only admins can view the user list
- Only admins can mark other users as admins
- Only admins can create categories
- Only logged in users can create gardens
- Only the user that created a garden can see the garden
- (e.g. you can only see the authentication and home pages if you are logged out)

**Comment by rachelself** [comment]
@elizabrock We would like to take this feature once it becomes available. @mattSpell and I are currently reading the docs for cancan in preparation for working on it.
