### ISSUE TITLE
Authentication User Story (Login)

### ISSUE THREAD

**Issue by TerrenceLJones** [elizamarcum/greenthumb#6]
LOGIN:

As a user,
I want my credentials to be authenticated
In order to log into the site.

Acceptance Criteria:

Able to input email and password
Validate that email and password are present
Password should be encrypted
Ability to retrieve data from Database
Valid email should match email in Database
Valid password should be a matched to password in Database
If user inputs an Invalid email or password a message will displayed letting them know of the error
If user inputs correct email and password the user dashboard will be displayed to the user

**Comment by elizamarcum** [comment]
Resolved by #acd82f6de5875a25708798af7bc9f08a5c2312c2
